// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsultorioClinico.Entities.Entities
{
    public partial class tbAreas
    {
        public tbAreas()
        {
            tbConsultorios = new HashSet<tbConsultorios>();
        }

        public int area_Id { get; set; }
        public string area_Nombre { get; set; }
        public int area_UsuCreacion { get; set; }
        public DateTime area_FechaCreacion { get; set; }
        public int? area_UsuModificacion { get; set; }
        public DateTime? area_FechaModificacion { get; set; }
        public bool? area_Estado { get; set; }

        public virtual tbUsuarios area_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios area_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbConsultorios> tbConsultorios { get; set; }
    }
}