// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsultorioClinico.Entities.Entities
{
    public partial class tbConsultorios
    {
        public tbConsultorios()
        {
            tbConsultas = new HashSet<tbConsultas>();
        }

        public int consltro_Id { get; set; }
        public string consltro_Nombre { get; set; }
        public int area_Id { get; set; }
        public int empe_Id { get; set; }
        public int consltro_UsuCreacion { get; set; }
        public DateTime consltro_FechaCreacion { get; set; }
        public int? consltro_UsuModificacion { get; set; }
        public DateTime? consltro_FechaModificacion { get; set; }
        public bool? consltro_Estado { get; set; }

        public virtual tbAreas area { get; set; }
        public virtual tbUsuarios consltro_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios consltro_UsuModificacionNavigation { get; set; }
        public virtual tbEmpleados empe { get; set; }
        public virtual ICollection<tbConsultas> tbConsultas { get; set; }
    }
}