// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsultorioClinico.Entities.Entities
{
    public partial class VW_Grafica_Sexo
    {
        public int? Masculino { get; set; }
        public int? Femenino { get; set; }
    }
}