// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace ConsultorioClinico.Entities.Entities
{
    public partial class VW_tbCargos
    {
        [Display(Name = "ID")]
        public int carg_Id { get; set; }

        [Display(Name = "Nombre")]
        public string carg_Nombre { get; set; }
        public int carg_UsuCreacion { get; set; }

        [Display(Name = "Usuario creación")]
        public string carg_UsuCreacionNombre { get; set; }

        [Display(Name = "Fecha creación")]
        public DateTime carg_FechaCreacion { get; set; }
        public int? carg_UsuModificacion { get; set; }

        [Display(Name = "Usuario modificación")]
        public string carg_UsuModificacionNombre { get; set; }

        [Display(Name = "Fecha modificación")]
        public DateTime? carg_FechaModificacion { get; set; }
        public bool carg_Estado { get; set; }
    }
}