// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsultorioClinico.Entities.Entities
{
    public partial class VW_tbMetodosPago
    {
        public int meto_Id { get; set; }
        public string meto_Nombre { get; set; }
    }
}