// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsultorioClinico.Entities.Entities
{
    public partial class VW_tbEmpleados
    {
        public int empe_Id { get; set; }
        public string empe_Nombres { get; set; }
        public string empe_Apellido { get; set; }
        public string empe_Identidad { get; set; }
        public string empe_Sexo { get; set; }
        public int estacivi_Id { get; set; }
        public string estacivi_Nombre { get; set; }
        public DateTime empe_FechaNacimiento { get; set; }
        public string muni_Id { get; set; }
        public string muni_Nombre { get; set; }
        public string depa_Id { get; set; }
        public string empe_Direccion { get; set; }
        public string empe_Telefono { get; set; }
        public string empe_Correo { get; set; }
        public DateTime empe_FechaInicio { get; set; }
        public DateTime? empe_FechaFinal { get; set; }
        public int carg_Id { get; set; }
        public string carg_Nombre { get; set; }
        public int clin_Id { get; set; }
        public string clin_Nombre { get; set; }
        public int empe_UsuCreacion { get; set; }
        public string empe_UsuCreacionNombre { get; set; }
        public int? empe_UsuModificacion { get; set; }
        public string empe_usuModificacionNombre { get; set; }
        public bool empe_Estado { get; set; }
    }
}