// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsultorioClinico.Entities.Entities
{
    public partial class VW_tbConsultas
    {
        public int cons_Id { get; set; }
        public DateTime cons_Inicio { get; set; }
        public DateTime cons_Final { get; set; }
        public int consltro_Id { get; set; }
        public string consltro_Nombre { get; set; }
        public int paci_Id { get; set; }
        public string cons_Paciente { get; set; }
        public decimal? cons_Costo { get; set; }
        public int cons_UsuCreacion { get; set; }
        public string cons_UsuarioCreacionNombre { get; set; }
        public int? cons_UsuModificacion { get; set; }
        public string cons_UsuarioModificacionNombre { get; set; }
    }
}