// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsultorioClinico.Entities.Entities
{
    public partial class VW_tbMedicamentos
    {
        public int medi_Id { get; set; }
        public string medi_Nombre { get; set; }
        public decimal medi_PrecioVenta { get; set; }
    }
}