// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsultorioClinico.Entities.Entities
{
    public partial class VW_tbDepartamentos
    {
        public string depa_Id { get; set; }
        public string depa_Nombre { get; set; }
        public int depa_UsuCreacion { get; set; }
        public string depa_UsuCreacionNombre { get; set; }
        public DateTime depa_FechaCreacion { get; set; }
        public int? depa_UsuModificacion { get; set; }
        public string depa_UsuModificacionNombre { get; set; }
        public DateTime? depa_FechaModificacion { get; set; }
    }
}