// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsultorioClinico.Entities.Entities
{
    public partial class VW_tbConsultas_Reporte
    {
        public DateTime Inicio { get; set; }
        public DateTime Final { get; set; }
        public string Paciente { get; set; }
        public string Médico { get; set; }
        public decimal? Costo { get; set; }
    }
}