// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsultorioClinico.Entities.Entities
{
    public partial class VW_tbPacientes
    {
        public string paci_NombreCompleto { get; set; }
        public int paci_Id { get; set; }
    }
}