// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsultorioClinico.Entities.Entities
{
    public partial class tbClinicas
    {
        public tbClinicas()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int clin_Id { get; set; }
        public string clin_Nombre { get; set; }
        public string muni_Id { get; set; }
        public string clin_Direccion { get; set; }
        public int empe_Id { get; set; }
        public int clin_UsuCreacion { get; set; }
        public DateTime clin_FechaCreacion { get; set; }
        public int? clin_UsuModificacion { get; set; }
        public DateTime? clin_FechaModificacion { get; set; }
        public bool? clin_Estado { get; set; }

        public virtual tbUsuarios clin_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios clin_UsuModificacionNavigation { get; set; }
        public virtual tbEmpleados empe { get; set; }
        public virtual tbMunicipios muni { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}