// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsultorioClinico.Entities.Entities
{
    public partial class tbConsultas
    {
        public tbConsultas()
        {
            tbFacturasDetalles = new HashSet<tbFacturasDetalles>();
        }

        public int cons_Id { get; set; }
        public DateTime cons_Inicio { get; set; }
        public DateTime cons_Final { get; set; }
        public int paci_Id { get; set; }
        public int consltro_Id { get; set; }
        public decimal? cons_Costo { get; set; }
        public int cons_UsuCreacion { get; set; }
        public DateTime cons_FechaCreacion { get; set; }
        public int? cons_UsuModificacion { get; set; }
        public DateTime? cons_FechaModificacion { get; set; }
        public bool? cons_Estado { get; set; }

        public virtual tbUsuarios cons_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios cons_UsuModificacionNavigation { get; set; }
        public virtual tbConsultorios consltro { get; set; }
        public virtual tbPacientes paci { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetalles { get; set; }
    }
}