// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsultorioClinico.Entities.Entities
{
    public partial class tbPacientes
    {
        public tbPacientes()
        {
            tbConsultas = new HashSet<tbConsultas>();
            tbFacturas = new HashSet<tbFacturas>();
        }

        public int paci_Id { get; set; }
        public string paci_Nombres { get; set; }
        public string paci_Apellidos { get; set; }
        public string paci_Identidad { get; set; }
        public string paci_TipoSangre { get; set; }
        public DateTime paci_FechaNacimiento { get; set; }
        public int estacivi_Id { get; set; }
        public string paci_Telefono { get; set; }
        public int paci_UsuCreacion { get; set; }
        public DateTime paci_FechaCreacion { get; set; }
        public int? paci_UsuModificacion { get; set; }
        public DateTime? paci_FechaModificacion { get; set; }
        public bool? paci_Estado { get; set; }

        public virtual tbEstadosCiviles estacivi { get; set; }
        public virtual tbUsuarios paci_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios paci_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbConsultas> tbConsultas { get; set; }
        public virtual ICollection<tbFacturas> tbFacturas { get; set; }
    }
}